title                    : "EPQM @ Siddhartha Lal"
description              : "**EPQM** is a condensed matter group at IISER Kolkata, led by Siddhartha Lal. We explore emergent phenomena in strongly correlated quantum matter."
url: "https://slal.iiserkol.ac.in" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ''
destination: ./docs
logo: "/assets/global/lightBanner.webp"
color-emoji:
  article: "🧬"
  interview: "🎙️"
  crossword: "🎳"
  comic: "🖍️"
  author: "🧑‍🔬"
  browse: "🥽"
  download: "⤵️"
  old: "🗓️"
  alert: "🧩"
  cloud: "☁️"
  desktop: "🖥️"
  copyright: "©️"
  speaker: "📢"
  newspaper: "🗞️"
  fire: "🔥"
  star: "🌠"
  flask: "⚗️"
  scientist: "🧑‍🔬"
  clip: "📎"
  hourglass: "⏳"

defaults:
  - scope:
      type: posts
    values:
      layout: posts
      excerpt: ""
  - scope:
      path: "pages/*"
    values:
      layout: pages
      excerpt: ""
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  math_engine: katex
  parse_block_html: true
  highlighter: rouge
plugins:
  - jekyll-sitemap
  - kramdown-math-katex
navbarShort:
  Updates: "/posts/"
  Research: "/research/"
  About: "/about/"
navbar:
  Updates: "/posts/"
  Research: "/research/"
  Publications: "/publications/"
  Teaching: "/teaching/"
  About: "/about/"
navbarLong:
  Updates: "/posts/"
  Research: "/research/"
  Teaching: "/teaching/"
  About: "/about/"
  Publications: "/publications/"
  Members: "/about/#members-of-epqm"
  Seminars: "/seminars/"
  Gallery: "/gallery/"
  External Resources: "/external-resources/"
  Fiction Recommendations: "/fiction-recommendations/"
membersdata: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQ3R8ASd0_9z41UXir7TE6FoQ6qUKJwWRrg_stP_QDnC3qb2rDN8SJiQrKWUmafvwyWHgXjwDUcUWKI/pub?output=tsv"
facebook: https://www.facebook.com/inscightmagazine
instagram: https://www.instagram.com/inscight_iiserkolkata/
twitter: https://x.com/InScightIISERK
exclude:
  - scripts
featured: /esiam/
